-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE userblogs_posts (
  ubp_page_id BIGINT NOT NULL,
  ubp_user_id BIGINT NOT NULL,
  ubp_username VARCHAR(255) NOT NULL,
  ubp_created TIMESTAMPTZ NOT NULL,
  ubp_last_touched TIMESTAMPTZ NOT NULL,
  ubp_comment_count INT DEFAULT 0 NOT NULL,
  ubp_last_comment TIMESTAMPTZ DEFAULT NULL,
  ubp_last_comment_user BIGINT DEFAULT NULL,
  PRIMARY KEY(ubp_page_id)
);

CREATE INDEX ubp_user_id ON userblogs_posts (ubp_user_id);

CREATE INDEX ubp_created ON userblogs_posts (ubp_created);


CREATE TABLE userblogs_comments (
  ubc_id BIGSERIAL NOT NULL,
  ubc_post_page_id BIGINT NOT NULL,
  ubc_parent_id BIGINT DEFAULT NULL,
  ubc_author BIGINT NOT NULL,
  ubc_created TIMESTAMPTZ NOT NULL,
  ubc_last_edited TIMESTAMPTZ NOT NULL,
  ubc_last_edited_user BIGINT DEFAULT NULL,
  ubc_edit_count INT DEFAULT 0 NOT NULL,
  ubc_content VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY(ubc_id)
);

CREATE INDEX ubc_post_page_id ON userblogs_comments (ubc_post_page_id);

CREATE INDEX ubc_parent_id ON userblogs_comments (ubc_parent_id);

CREATE INDEX ubc_author ON userblogs_comments (ubc_author);


CREATE TABLE userblogs_comment_likes (
  ubl_comment_id BIGINT NOT NULL,
  ubl_user_id BIGINT NOT NULL,
  ubl_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ubl_comment_id, ubl_user_id)
);

CREATE INDEX ubl_user_id ON userblogs_comment_likes (ubl_user_id);


CREATE TABLE userblogs_comment_favorites (
  ubf_comment_id BIGINT NOT NULL,
  ubf_user_id BIGINT NOT NULL,
  ubf_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ubf_comment_id, ubf_user_id)
);

CREATE INDEX ubf_user_id ON userblogs_comment_favorites (ubf_user_id);
