-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_posts.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE userblogs_posts (
  ubp_page_id BIGINT NOT NULL,
  ubp_user_id BIGINT NOT NULL,
  ubp_username VARCHAR(255) NOT NULL,
  ubp_created TIMESTAMPTZ NOT NULL,
  ubp_last_touched TIMESTAMPTZ NOT NULL,
  ubp_comment_count INT DEFAULT 0 NOT NULL,
  ubp_last_comment TIMESTAMPTZ DEFAULT NULL,
  ubp_last_comment_user BIGINT DEFAULT NULL,
  PRIMARY KEY(ubp_page_id)
);

CREATE INDEX ubp_user_id ON userblogs_posts (ubp_user_id);

CREATE INDEX ubp_created ON userblogs_posts (ubp_created);
