-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_comments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE userblogs_comments (
  ubc_id BIGSERIAL NOT NULL,
  ubc_post_page_id BIGINT NOT NULL,
  ubc_parent_id BIGINT DEFAULT NULL,
  ubc_author BIGINT NOT NULL,
  ubc_created TIMESTAMPTZ NOT NULL,
  ubc_last_edited TIMESTAMPTZ NOT NULL,
  ubc_last_edited_user BIGINT DEFAULT NULL,
  ubc_edit_count INT DEFAULT 0 NOT NULL,
  ubc_content VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY(ubc_id)
);

CREATE INDEX ubc_post_page_id ON userblogs_comments (ubc_post_page_id);

CREATE INDEX ubc_parent_id ON userblogs_comments (ubc_parent_id);

CREATE INDEX ubc_author ON userblogs_comments (ubc_author);
