-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_comment_likes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE userblogs_comment_likes (
  ubl_comment_id BIGINT NOT NULL,
  ubl_user_id BIGINT NOT NULL,
  ubl_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ubl_comment_id, ubl_user_id)
);

CREATE INDEX ubl_user_id ON userblogs_comment_likes (ubl_user_id);
