-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_posts (
  ubp_page_id BIGINT UNSIGNED NOT NULL,
  ubp_user_id BIGINT UNSIGNED NOT NULL,
  ubp_username VARCHAR(255) NOT NULL,
  ubp_created BINARY(14) NOT NULL,
  ubp_last_touched BINARY(14) NOT NULL,
  ubp_comment_count INT UNSIGNED DEFAULT 0 NOT NULL,
  ubp_last_comment BINARY(14) DEFAULT NULL,
  ubp_last_comment_user BIGINT UNSIGNED DEFAULT NULL,
  INDEX ubp_user_id (ubp_user_id),
  INDEX ubp_created (ubp_created),
  PRIMARY KEY(ubp_page_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/userblogs_comments (
  ubc_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ubc_post_page_id BIGINT UNSIGNED NOT NULL,
  ubc_parent_id BIGINT UNSIGNED DEFAULT NULL,
  ubc_author BIGINT UNSIGNED NOT NULL,
  ubc_created BINARY(14) NOT NULL,
  ubc_last_edited BINARY(14) NOT NULL,
  ubc_last_edited_user BIGINT UNSIGNED DEFAULT NULL,
  ubc_edit_count INT UNSIGNED DEFAULT 0 NOT NULL,
  ubc_content VARCHAR(255) DEFAULT NULL,
  INDEX ubc_post_page_id (ubc_post_page_id),
  INDEX ubc_parent_id (ubc_parent_id),
  INDEX ubc_author (ubc_author),
  PRIMARY KEY(ubc_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/userblogs_comment_likes (
  ubl_comment_id BIGINT UNSIGNED NOT NULL,
  ubl_user_id BIGINT UNSIGNED NOT NULL,
  ubl_created BINARY(14) NOT NULL,
  INDEX ubl_user_id (ubl_user_id),
  PRIMARY KEY(ubl_comment_id, ubl_user_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/userblogs_comment_favorites (
  ubf_comment_id BIGINT UNSIGNED NOT NULL,
  ubf_user_id BIGINT UNSIGNED NOT NULL,
  ubf_created BINARY(14) NOT NULL,
  INDEX ubf_user_id (ubf_user_id),
  PRIMARY KEY(ubf_comment_id, ubf_user_id)
) /*$wgDBTableOptions*/;
