-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_posts (
  ubp_page_id BIGINT UNSIGNED NOT NULL,
  ubp_user_id BIGINT UNSIGNED NOT NULL,
  ubp_username VARCHAR(255) NOT NULL,
  ubp_created BLOB NOT NULL,
  ubp_last_touched BLOB NOT NULL,
  ubp_comment_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  ubp_last_comment BLOB DEFAULT NULL,
  ubp_last_comment_user BIGINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY(ubp_page_id)
);

CREATE INDEX ubp_user_id ON /*_*/userblogs_posts (ubp_user_id);

CREATE INDEX ubp_created ON /*_*/userblogs_posts (ubp_created);


CREATE TABLE /*_*/userblogs_comments (
  ubc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ubc_post_page_id BIGINT UNSIGNED NOT NULL,
  ubc_parent_id BIGINT UNSIGNED DEFAULT NULL,
  ubc_author BIGINT UNSIGNED NOT NULL,
  ubc_created BLOB NOT NULL,
  ubc_last_edited BLOB NOT NULL,
  ubc_last_edited_user BIGINT UNSIGNED DEFAULT NULL,
  ubc_edit_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  ubc_content VARCHAR(255) DEFAULT NULL
);

CREATE INDEX ubc_post_page_id ON /*_*/userblogs_comments (ubc_post_page_id);

CREATE INDEX ubc_parent_id ON /*_*/userblogs_comments (ubc_parent_id);

CREATE INDEX ubc_author ON /*_*/userblogs_comments (ubc_author);


CREATE TABLE /*_*/userblogs_comment_likes (
  ubl_comment_id BIGINT UNSIGNED NOT NULL,
  ubl_user_id BIGINT UNSIGNED NOT NULL,
  ubl_created BLOB NOT NULL,
  PRIMARY KEY(ubl_comment_id, ubl_user_id)
);

CREATE INDEX ubl_user_id ON /*_*/userblogs_comment_likes (ubl_user_id);


CREATE TABLE /*_*/userblogs_comment_favorites (
  ubf_comment_id BIGINT UNSIGNED NOT NULL,
  ubf_user_id BIGINT UNSIGNED NOT NULL,
  ubf_created BLOB NOT NULL,
  PRIMARY KEY(ubf_comment_id, ubf_user_id)
);

CREATE INDEX ubf_user_id ON /*_*/userblogs_comment_favorites (ubf_user_id);
