-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_comment_favorites.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_comment_favorites (
  ubf_comment_id BIGINT UNSIGNED NOT NULL,
  ubf_user_id BIGINT UNSIGNED NOT NULL,
  ubf_created BLOB NOT NULL,
  PRIMARY KEY(ubf_comment_id, ubf_user_id)
);

CREATE INDEX ubf_user_id ON /*_*/userblogs_comment_favorites (ubf_user_id);
