-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_comments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_comments (
  ubc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ubc_post_page_id BIGINT UNSIGNED NOT NULL,
  ubc_parent_id BIGINT UNSIGNED DEFAULT NULL,
  ubc_author BIGINT UNSIGNED NOT NULL,
  ubc_created BLOB NOT NULL,
  ubc_last_edited BLOB NOT NULL,
  ubc_last_edited_user BIGINT UNSIGNED DEFAULT NULL,
  ubc_edit_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  ubc_content VARCHAR(255) DEFAULT NULL
);

CREATE INDEX ubc_post_page_id ON /*_*/userblogs_comments (ubc_post_page_id);

CREATE INDEX ubc_parent_id ON /*_*/userblogs_comments (ubc_parent_id);

CREATE INDEX ubc_author ON /*_*/userblogs_comments (ubc_author);
