-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_posts.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_posts (
  ubp_page_id BIGINT UNSIGNED NOT NULL,
  ubp_user_id BIGINT UNSIGNED NOT NULL,
  ubp_username VARCHAR(255) NOT NULL,
  ubp_created BLOB NOT NULL,
  ubp_last_touched BLOB NOT NULL,
  ubp_comment_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  ubp_last_comment BLOB DEFAULT NULL,
  ubp_last_comment_user BIGINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY(ubp_page_id)
);

CREATE INDEX ubp_user_id ON /*_*/userblogs_posts (ubp_user_id);

CREATE INDEX ubp_created ON /*_*/userblogs_posts (ubp_created);
