-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_posts.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_posts (
  ubp_page_id BIGINT UNSIGNED NOT NULL,
  ubp_user_id BIGINT UNSIGNED NOT NULL,
  ubp_username VARCHAR(255) NOT NULL,
  ubp_created BINARY(14) NOT NULL,
  ubp_last_touched BINARY(14) NOT NULL,
  ubp_comment_count INT UNSIGNED DEFAULT 0 NOT NULL,
  ubp_last_comment BINARY(14) DEFAULT NULL,
  ubp_last_comment_user BIGINT UNSIGNED DEFAULT NULL,
  INDEX ubp_user_id (ubp_user_id),
  INDEX ubp_created (ubp_created),
  PRIMARY KEY(ubp_page_id)
) /*$wgDBTableOptions*/;
