-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_comments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_comments (
  ubc_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ubc_post_page_id BIGINT UNSIGNED NOT NULL,
  ubc_parent_id BIGINT UNSIGNED DEFAULT NULL,
  ubc_author BIGINT UNSIGNED NOT NULL,
  ubc_created BINARY(14) NOT NULL,
  ubc_last_edited BINARY(14) NOT NULL,
  ubc_last_edited_user BIGINT UNSIGNED DEFAULT NULL,
  ubc_edit_count INT UNSIGNED DEFAULT 0 NOT NULL,
  ubc_content VARCHAR(255) DEFAULT NULL,
  INDEX ubc_post_page_id (ubc_post_page_id),
  INDEX ubc_parent_id (ubc_parent_id),
  INDEX ubc_author (ubc_author),
  PRIMARY KEY(ubc_id)
) /*$wgDBTableOptions*/;
