-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/userblogs_comment_likes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/userblogs_comment_likes (
  ubl_comment_id BIGINT UNSIGNED NOT NULL,
  ubl_user_id BIGINT UNSIGNED NOT NULL,
  ubl_created BINARY(14) NOT NULL,
  INDEX ubl_user_id (ubl_user_id),
  PRIMARY KEY(ubl_comment_id, ubl_user_id)
) /*$wgDBTableOptions*/;
